name: Dependency Review

on:
  pull_request:
  merge_group:

jobs:
  dependency-review:
    uses: gravitational/shared-workflows/.github/workflows/dependency-review.yaml@main
    permissions:
      contents: read
      pull-requests: write
